#### 1. One word at a time

In [6]:
import pandas as pd
text = ['cat','dog','fish','bird','cat','dog']
data = pd.get_dummies(text)
print(data)
print('-'*30)
print(data.keys())

   bird  cat  dog  fish
0     0    1    0     0
1     0    0    1     0
2     0    0    0     1
3     1    0    0     0
4     0    1    0     0
5     0    0    1     0
------------------------------
Index(['bird', 'cat', 'dog', 'fish'], dtype='object')


#### 2. Whole sentence at a time

In [12]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs','i hate cats','i like turtles','i love the dogs']
# Reshape the data
text = np.array(text)
print(text.shape)
# Adding an extra dimension
text = np.reshape(text,(-1,1))
print(text.shape)

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.toarray())
print([i[3:] for i in encoder.get_feature_names_out()])

(4,)
(4, 1)
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['i hate cats', 'i like turtles', 'i love dogs', 'i love the dogs']


#### 3. Tokenized Sentence

In [18]:
text = [['this','is','good'],['but','its','fine']]
encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)
print(one_hot.toarray())
print('-'*30)

print([i[3:] for i in encoder.get_feature_names_out()])

[[0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0.]]
------------------------------
['but', 'this', 'is', 'its', 'fine', 'good']


In [19]:
pd.DataFrame(one_hot.toarray(),columns = [i[3:] for i in encoder.get_feature_names_out()])

but  this   is  its  fine  good
0  0.0   1.0  1.0  0.0   0.0   1.0
1  1.0   0.0  0.0  1.0   1.0   0.0